<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-CU28HKJ" ignored="0" name="用户管理系统接口" tests="6" failures="5" timestamp="2020-04-01T22:41:26 CST" time="20.935" errors="0">
  <testcase name="run" time="2.233" classname="itest.APITest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [请求错误]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [请求错误]
at itest.APITest.doCase(APITest.java:37)
at itest.APITest.run(APITest.java:25)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- run -->
  <testcase name="run" time="2.073" classname="itest.APITest">
    <failure type="java.lang.AssertionError" message="expected [8] but found [请求异常，发生错误！]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [请求异常，发生错误！]
at itest.APITest.doCase(APITest.java:34)
at itest.APITest.run(APITest.java:25)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- run -->
  <testcase name="run" time="2.074" classname="itest.APITest">
    <failure type="java.lang.AssertionError" message="expected [[{&amp;quot;id&amp;quot;:1,&amp;quot;username&amp;quot;:&amp;quot;lewis&amp;quot;,&amp;quot;password&amp;quot;:&amp;quot;123&amp;quot;,&amp;quot;sex&amp;quot;:&amp;quot;0&amp;quot;,&amp;quot;age&amp;quot;:&amp;quot;33&amp;quot;,&amp;quot;permission&amp;quot;:&amp;quot;1&amp;quot;,&amp;quot;isDelete&amp;quot;:&amp;quot;0&amp;quot;}]] but found [请求错误]">
      <![CDATA[java.lang.AssertionError: expected [[{"id":1,"username":"lewis","password":"123","sex":"0","age":"33","permission":"1","isDelete":"0"}]] but found [请求错误]
at itest.APITest.doCase(APITest.java:37)
at itest.APITest.run(APITest.java:25)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- run -->
  <testcase name="run" time="2.053" classname="itest.APITest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [请求错误]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [请求错误]
at itest.APITest.doCase(APITest.java:37)
at itest.APITest.run(APITest.java:25)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- run -->
  <testcase name="run" time="2.072" classname="itest.APITest">
    <failure type="java.lang.AssertionError" message="expected [8] but found [请求异常，发生错误！]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [请求异常，发生错误！]
at itest.APITest.doCase(APITest.java:34)
at itest.APITest.run(APITest.java:25)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- run -->
  <testcase name="f" time="10.343" classname="itest.WebTest"/>
</testsuite> <!-- 用户管理系统接口 -->
